# Introducing Pandas Objects

In [1]:
import pandas as pd
import numpy as np

## The Pandas Series Object

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
data[1]

0.5

In [6]:
data = pd.Series([0.25, 0.5, 0.75, 1],
                index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [7]:
data['b']

0.5

In [8]:
population_dict = {'California': 38332521,
                 'Texas': 26448193,
                 'New York': 19651127,
                 'Florida': 19552860,
                 'Illinois': 12882135}

population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [9]:
pd.Series(3.14, [1, 2, 3, 4])

1    3.14
2    3.14
3    3.14
4    3.14
dtype: float64

In [10]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
 'Florida': 170312, 'Illinois': 149995}

In [11]:
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [12]:
states = pd.DataFrame({
    'population': population,
    'area': area
})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [13]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [14]:
states.columns

Index(['population', 'area'], dtype='object')

In [15]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

## Constructing DataFrame objects

#### From a single Series object

In [16]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

#### From a list of dicts

In [17]:
data = [{'a':i, 'b':2*i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [18]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [19]:
pd.DataFrame({'population': population,
              'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [20]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.582509  0.864324
b  0.749224  0.320780
c  0.260142  0.013435

In [21]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [22]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## The Pandas Index Object

In [23]:
ind = pd.Index([2, 4, 5, 7, 9])
ind

Int64Index([2, 4, 5, 7, 9], dtype='int64')

In [24]:
ind.size

5

In [25]:
ind.shape

(5,)

## Index as ordered set

In [26]:
A = pd.Index([1, 3, 5, 7, 9])
B = pd.Index([2, 3, 5, 7, 8])

In [27]:
A.intersection(B)

Int64Index([3, 5, 7], dtype='int64')

In [28]:
A.union(B)

Int64Index([1, 2, 3, 5, 7, 8, 9], dtype='int64')

In [29]:
A.difference(B)

Int64Index([1, 9], dtype='int64')

# Data Indexing and Selection

### Series as dictionary

In [30]:
data = pd.Series(np.linspace(0, 1, 5),
                index=['a', 'b', 'c', 'd', 'e'])

In [31]:
data

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [32]:
data['b']

0.25

In [33]:
'a' in data

True

In [34]:
data.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [35]:
list(data.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [36]:
data['a'] = 69

In [37]:
data

a    69.00
b     0.25
c     0.50
d     0.75
e     1.00
dtype: float64

In [38]:
data['a':'c']

a    69.00
b     0.25
c     0.50
dtype: float64

In [39]:
data[0:2]

a    69.00
b     0.25
dtype: float64

In [40]:
data[(data > 0.3) & (data < 0.8)]

c    0.50
d    0.75
dtype: float64

In [41]:
data[['a', 'e']]

a    69.0
e     1.0
dtype: float64

### Indexers: loc, iloc, and ix

In [42]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [43]:
data[1]

'a'

In [44]:
data[1:3]

3    b
5    c
dtype: object

In [45]:
data.loc[1]

'a'

In [46]:
data.loc[1:3]

1    a
3    b
dtype: object

In [47]:
data.iloc[1]

'b'

In [48]:
data.iloc[1:3]

3    b
5    c
dtype: object

## Data Selection in DataFrame


In [49]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                 'New York': 141297, 'Florida': 170312,
                 'Illinois': 149995})

In [50]:
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})

In [51]:
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [52]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [53]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [54]:
data['density'] = data['pop'] / data['area']

In [55]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

## DataFrame as two-dimensional array

In [56]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [57]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [58]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [59]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

# Handling Missing Data
***

### None: Pythonic missing data


In [60]:
data = np.array([1, None, 3, 4])
data

array([1, None, 3, 4], dtype=object)

### NaN: Missing numerical data

In [61]:
data = np.array([1, np.nan, 3, 4])
data.dtype

dtype('float64')

In [62]:
data.sum()

nan

In [63]:
np.nansum(data)

8.0

## Operating on Null Values

In [64]:
data = pd.Series([1, np.nan, 3, None])

In [65]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [66]:
data[data.notnull()]

0    1.0
2    3.0
dtype: float64

In [67]:
data.dropna()

0    1.0
2    3.0
dtype: float64

In [68]:
df = pd.DataFrame([[1, np.nan, 2],
                 [2, 3, 5],
                 [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [69]:
df.dropna() # drop all rows in which any null value is present

0    1  2
1  2.0  3.0  5

In [70]:
df.dropna(axis=1) # drop all columns in which any null value is present

2
0  2
1  5
2  6

In [71]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [72]:
df.dropna(how='all', axis=1)

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [73]:
df.dropna(how='any', axis=1)

2
0  2
1  5
2  6

## Filling null values

In [74]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [75]:
data.fillna(69)

a     1.0
b    69.0
c     2.0
d    69.0
e     3.0
dtype: float64

In [76]:
# forward-fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [77]:
# back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [78]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [79]:
df.fillna(method='ffill', axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

# A Multiply Indexed Series

In [80]:
index = [('California', 2000), ('California', 2010),
 ('New York', 2000), ('New York', 2010),
 ('Texas', 2000), ('Texas', 2010)]

In [81]:
populations = [33871648, 37253956,
 18976457, 19378102,
 20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [82]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [83]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [84]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [85]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

## Methods of MultiIndex Creation


In [87]:
df = pd.DataFrame(np.random.rand(4, 2),
                 index=[list('aabb'), [1, 2, 1, 2]],
                 columns=['data1', 'data2'])
df

data1     data2
a 1  0.571288  0.759522
  2  0.181397  0.729165
b 1  0.233260  0.940797
  2  0.563699  0.271510

In [88]:
data = {('California', 2000): 33871648,
         ('California', 2010): 37253956,
         ('Texas', 2000): 20851820,
         ('Texas', 2010): 25145561,
         ('New York', 2000): 18976457,
         ('New York', 2010): 19378102}

pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [89]:
pd.MultiIndex.from_arrays([list('aabb'), [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [90]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [91]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2, 3]])

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('b', 3)],
           )